services:
  monorepo:
    build: .
    command: npm run local
    volumes:
      - .:/app
      - npm-cache:/root/.npm
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING
      - CLOUD_REGION
      - CLOUD_ACCESS_KEY_ID
      - CLOUD_SECRET_ACCESS_KEY
      - CLOUD_ENDPOINT_URL
      - NODE_ENV
      - LOG_LEVEL
      - OTEL_EXPORTER_OTLP_ENDPOINT
  
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,iam,ssm,logs
      - DEBUG=1
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./localstack:/var/lib/localstack
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  npm-cache:
  localstack-data: