name: CI

on:
  push:
    branches:
      - '**'
  pull_request: {}

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Instalar dependências
        run: npm ci

      - name: Analisar lint
        run: npm run lint

      - name: Executar testes
        run: npm run test

      - name: Compilar pacotes
        run: npm run build
